# Generated by Django 5.0.1 on 2024-02-05 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booking',
        ),
        migrations.AddField(
            model_name='customer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='LastName', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_diners',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
