# Generated by Django 5.0.1 on 2024-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_remove_customer_booking_customer_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
