# Generated by Django 5.0.1 on 2024-02-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_customer_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_no',
        ),
    ]
