# Generated by Django 5.0.1 on 2024-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
